version: '3.8'
name: n5-generic-stack
services:
  postgres:  
    container_name: postgres  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
    ports:  
      - "5432:5432"  
    expose:
      - "5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - n5-network  
  pgadmin:  
    container_name: pgadmin4_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: root  
    ports:  
      - "5050:80"
    networks:
      - n5-network   

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - n5-network   

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - n5-network  
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  redis-local:
    image: redis:latest
    container_name: redis
    ports:
        - 6379:6379
    networks:
      - n5-network
      
networks:
  n5-network:
    name: n5-network        